### PR TITLE
update embedded hal to 1.0.0

### PR DESCRIPTION
**Pull request by ryankurte**
also swaps structopt to clap and updates a few other deps

### CODE REVIEW

**Comment by SimonIT** [comment]
Is there any reason why this PR isn't merged? We are evaluating, as a master project, if we can use this crate as an independent interface

**Comment by SimonIT** [comment]
@ryankurte @henrikssn

**Comment by ryankurte** [comment]
howdy, now we have an e-h 1.0 release it's just a matter of finding the time to update radio-hal and the downstream packages... would be delighted to accept PRs if y'all are interested in contributing ^_^

**Comment by ryankurte** [comment]
thanks @SimonIT! still probably will update some radio drivers and test prior to release, but, hopefully this helps ^_^

(also very curious about what you're working on that this would be useful for?)

**Pull request merged**
